### ISSUE TITLE
Line Chart: Hardcoded implementation 

### ISSUE THREAD

**Issue by PCXDME** [Rostlab/JS18_ProjectB_Group4#7]

**Comment by PCXDME** [comment]
# Todo
- [x] Change marker symbol
- [x] Change marker size
- [x] Change marker opacity
- [x] Change line color
- [x] Change line width
- [x] Change line shape
- [x] Change line smoothing
- [x] Change line dash
- [x] Change scatter mode (Show/hide marker, line, text)
