### ISSUE TITLE
Scatter Plot: Hardcoded implementation 

### ISSUE THREAD

**Issue by PCXDME** [Rostlab/JS18_ProjectB_Group4#9]

**Comment by PCXDME** [comment]
# Todo
- [x] Change marker symbol
- [x] Change marker size
- [x] Change marker opacity
- [x] Change scatter mode (Show/hide marker, line, text)
